name: Upload web files to S3

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
        - name: Deploying application to Amazon S3
          uses: dvelasquez/deploy-s3-action@main
          with:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
           AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
           BUCKET_PATH: "" # Or to upload a pull_request: "/pr/${{github.event.number}}"
           DIST_LOCATION_CODE: ./dist